import {createHmac,timingSafeEqual,randomUUID} from "node:crypto";
import {initializeApp,getApps,cert} from "firebase-admin/app";
import {getFirestore,FieldValue} from "firebase-admin/firestore";
let firestore;
function db(){if(firestore)return firestore;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("Firebase is not configured.");const sa=JSON.parse(raw);if(sa.private_key)sa.private_key=sa.private_key.replace(/\\n/g,"\n");if(!getApps().length)initializeApp({credential:cert(sa)});firestore=getFirestore();return firestore;}
function getSession(req){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)return null;const part=(req.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("bd_session="));if(!part)return null;let value;try{value=decodeURIComponent(part.slice(11));}catch{return null;}const dot=value.lastIndexOf(".");if(dot<1)return null;const payload=value.slice(0,dot),sig=value.slice(dot+1),expected=createHmac("sha256",secret).update(payload).digest("base64url"),a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{const p=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));return p.exp>Date.now()/1000?{id:String(p.id),username:String(p.username||"").slice(0,32),globalName:String(p.globalName||"").slice(0,64)}:null;}catch{return null;}}
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
const TYPES=["clan_membership","tryout_staff","other_recruitment"];
const clean=(v,n)=>String(v||"").trim().replace(/[\u0000-\u001f\u007f]/g,"").slice(0,n);
export default async req=>{const user=getSession(req);if(!user)return json({error:"Sign in with Discord to continue."},401);try{const store=db(),ref=store.collection("webApplications");if(req.method==="GET"){const snap=await ref.where("discordId","==",user.id).get();const applications=snap.docs.map(d=>{const a=d.data();return{id:d.id,type:a.type,status:a.status,submittedAt:a.submittedAt?.toMillis?.()||Number(a.submittedAt)||0,updatedAt:a.updatedAt?.toMillis?.()||Number(a.updatedAt)||0,answers:a.answers||{},staffFeedback:a.staffFeedback||null};}).sort((a,b)=>b.submittedAt-a.submittedAt);return json({applications});}
if(req.method!=="POST")return json({error:"Method not allowed."},405);let body;try{body=await req.json();}catch{return json({error:"Invalid request."},400);}const type=clean(body.type,40),roblox=clean(body.robloxUsername,32),motivation=clean(body.motivation,1200),experience=clean(body.experience,1000),availability=clean(body.availability,300);if(!TYPES.includes(type))return json({error:"Choose a valid application type."},400);if(!roblox||!motivation||motivation.length<20)return json({error:"Add your Roblox username and a little more detail about why you're applying."},400);if(type==="tryout_staff"&&(!experience||!availability))return json({error:"Tryout staff applications also need experience and availability."},400);const existing=await ref.where("discordId","==",user.id).get();const pending=existing.docs.filter(d=>["pending","reviewing","needs_info"].includes(d.data().status));if(pending.length>=3)return json({error:"You already have three applications awaiting a decision. Please wait for staff to review them."},429);const now=Date.now(),doc=await ref.add({discordId:user.id,discordUsername:user.username,discordGlobalName:user.globalName||null,type,status:"pending",answers:{robloxUsername:roblox,motivation,experience:experience||null,availability:availability||null},submittedAt:now,updatedAt:now,staffFeedback:null,reviewerDiscordId:null,reviewedAt:null});return json({ok:true,id:doc.id,message:"Application submitted. You can follow its status from this page."},201);
}catch(e){console.error("Applications endpoint failed:",e);return json({error:"Applications are temporarily unavailable."},500);}};
