import {getSessionUser} from "./_shared/discord-auth.mjs";
import {hasWebsitePermission} from "./_shared/staff-access.mjs";
import {initializeApp,getApps,cert} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
let firestore;
function db(){if(firestore)return firestore;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("Firebase is not configured.");const sa=JSON.parse(raw);if(sa.private_key)sa.private_key=sa.private_key.replace(/\\n/g,"\n");if(!getApps().length)initializeApp({credential:cert(sa)});firestore=getFirestore();return firestore;}
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
const statuses=["reviewing","needs_info","accepted","rejected"];
export default async req=>{const u=getSessionUser(req);if(!u)return json({error:"Sign in with Discord first."},401);const store=db();if(!await hasWebsitePermission(u,"applications.review","APPLICATION_REVIEW_ROLE_IDS"))return json({error:"You do not have permission to review applications."},403);try{const col=store.collection("webApplications");if(req.method==="GET"){const snap=await col.orderBy("submittedAt","desc").limit(100).get();return json({applications:snap.docs.map(d=>({id:d.id,...d.data()}))});}if(req.method!=="PATCH")return json({error:"Method not allowed."},405);let body;try{body=await req.json();}catch{return json({error:"Invalid request."},400);}const id=String(body.id||""),status=String(body.status||""),feedback=String(body.feedback||"").trim().slice(0,800);if(!/^[A-Za-z0-9]{15,40}$/.test(id)||!statuses.includes(status))return json({error:"Invalid application update."},400);const ref=col.doc(id),snap=await ref.get();if(!snap.exists)return json({error:"Application not found."},404);await ref.update({status,staffFeedback:feedback||null,reviewerDiscordId:u.id,reviewedAt:Date.now(),updatedAt:Date.now()});await store.collection("webAuditLogs").add({action:"application_review",applicationId:id,targetDiscordId:snap.data().discordId,reviewerDiscordId:u.id,status,createdAt:Date.now()});return json({ok:true});}catch(e){console.error("Application review failed:",e);return json({error:"The review action could not be completed."},500);}};
