import {createHmac,timingSafeEqual} from "node:crypto";
import {initializeApp,getApps,cert} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
let firestore;
function db(){if(firestore)return firestore;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("Firebase is not configured.");const sa=JSON.parse(raw);if(sa.private_key)sa.private_key=sa.private_key.replace(/\\n/g,"\n");if(!getApps().length)initializeApp({credential:cert(sa)});firestore=getFirestore();return firestore;}
function user(req){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)return null;const part=(req.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("bd_session="));if(!part)return null;let v;try{v=decodeURIComponent(part.slice(11));}catch{return null;}const i=v.lastIndexOf(".");if(i<1)return null;const p=v.slice(0,i),s=v.slice(i+1),e=createHmac("sha256",secret).update(p).digest("base64url"),a=Buffer.from(s),b=Buffer.from(e);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.exp>Date.now()/1000?{id:String(x.id),roles:Array.isArray(x.roles)?x.roles.map(String):[]}:null;}catch{return null;}}
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
function authorised(u){const allowed=(process.env.APPLICATION_REVIEW_ROLE_IDS||"").split(",").map(x=>x.trim()).filter(Boolean);return allowed.length>0&&u.roles.some(r=>allowed.includes(r));}
const statuses=["reviewing","needs_info","accepted","rejected"];
export default async req=>{const u=user(req);if(!u)return json({error:"Sign in with Discord first."},401);if(!authorised(u))return json({error:"You do not have permission to review applications."},403);try{const store=db(),col=store.collection("webApplications");if(req.method==="GET"){const snap=await col.orderBy("submittedAt","desc").limit(100).get();return json({applications:snap.docs.map(d=>({id:d.id,...d.data()}))});}if(req.method!=="PATCH")return json({error:"Method not allowed."},405);let body;try{body=await req.json();}catch{return json({error:"Invalid request."},400);}const id=String(body.id||""),status=String(body.status||""),feedback=String(body.feedback||"").trim().slice(0,800);if(!/^[A-Za-z0-9]{15,40}$/.test(id)||!statuses.includes(status))return json({error:"Invalid application update."},400);const ref=col.doc(id),snap=await ref.get();if(!snap.exists)return json({error:"Application not found."},404);await ref.update({status,staffFeedback:feedback||null,reviewerDiscordId:u.id,reviewedAt:Date.now(),updatedAt:Date.now()});await store.collection("webAuditLogs").add({action:"application_review",applicationId:id,targetDiscordId:snap.data().discordId,reviewerDiscordId:u.id,status,createdAt:Date.now()});return json({ok:true});}catch(e){console.error("Application review failed:",e);return json({error:"The review action could not be completed."},500);}};
