import {createHmac,timingSafeEqual,randomUUID} from "node:crypto";
import {initializeApp,getApps,cert} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
let firestore;function db(){if(firestore)return firestore;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("Firebase is not configured.");const sa=JSON.parse(raw);if(sa.private_key)sa.private_key=sa.private_key.replace(/\\n/g,"\n");if(!getApps().length)initializeApp({credential:cert(sa)});firestore=getFirestore();return firestore;}
function user(req){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)return null;const part=(req.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("bd_session="));if(!part)return null;let v;try{v=decodeURIComponent(part.slice(11));}catch{return null;}const i=v.lastIndexOf(".");if(i<1)return null;const p=v.slice(0,i),s=v.slice(i+1),e=createHmac("sha256",secret).update(p).digest("base64url"),a=Buffer.from(s),b=Buffer.from(e);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.exp>Date.now()/1000?{id:String(x.id),username:String(x.username||""),globalName:String(x.globalName||""),roles:Array.isArray(x.roles)?x.roles.map(String):[]}:null;}catch{return null;}}
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
const clean=(v,n)=>String(v||"").trim().replace(/[\u0000-\u001f\u007f]/g,"").slice(0,n);
const validDate=v=>typeof v==="number"&&Number.isFinite(v)&&v>Date.now()-3600000&&v<Date.now()+366*86400000;
function canManage(u){const ids=(process.env.EVENT_MANAGE_ROLE_IDS||process.env.APPLICATION_REVIEW_ROLE_IDS||"").split(",").map(x=>x.trim()).filter(Boolean);return ids.length>0&&u?.roles?.some(x=>ids.includes(x));}
function safeEvent(d,id){return{id,title:clean(d.title,100),category:clean(d.category,32),description:clean(d.description,1800),location:clean(d.location,140),startsAt:Number(d.startsAt)||0,endsAt:Number(d.endsAt)||0,status:clean(d.status,20),capacity:Math.max(0,Number(d.capacity)||0),registrationOpen:d.registrationOpen!==false,createdAt:Number(d.createdAt)||0};}
export default async req=>{try{const store=db(),col=store.collection("webEvents");if(req.method==="GET"){const u=user(req);const snap=await col.orderBy("startsAt","asc").limit(100).get();const events=[];for(const doc of snap.docs){const e=safeEvent(doc.data(),doc.id);if(e.status==="cancelled"&&!canManage(u))continue;let registration=null;if(u){const reg=await doc.ref.collection("registrations").doc(u.id).get();if(reg.exists)registration={status:clean(reg.data().status,20)||"registered",registeredAt:Number(reg.data().registeredAt)||0};}events.push({...e,registration});}return json({events,signedIn:!!u,canManage:canManage(u)});}
const u=user(req);if(!u)return json({error:"Sign in with Discord to continue."},401);
if(req.method==="POST"){let b;try{b=await req.json();}catch{return json({error:"Invalid request."},400);}const id=clean(b.eventId,100);if(id){const ref=col.doc(id),snap=await ref.get();if(!snap.exists)return json({error:"Event not found."},404);const e=snap.data();if(e.status!=="published"||e.registrationOpen===false||Number(e.startsAt)<=Date.now())return json({error:"Registration is closed for this event."},409);const profile=await store.collection("webProfiles").doc(u.id).get(),p=profile.exists?profile.data():{};if(!p.robloxUserId||!p.robloxUsername)return json({error:"Link and verify your Roblox account before registering."},400);const rr=ref.collection("registrations").doc(u.id);const created=await store.runTransaction(async tx=>{const existing=await tx.get(rr);if(existing.exists)return false;if(Number(e.capacity)>0){const countSnap=await tx.get(ref.collection("registrations"));if(countSnap.size>=Number(e.capacity))throw new Error("This event has reached its registration capacity.");}tx.create(rr,{discordId:u.id,discordUsername:u.username,discordGlobalName:u.globalName||null,robloxUserId:String(p.robloxUserId),robloxUsername:String(p.robloxUsername).slice(0,32),status:"registered",registeredAt:Date.now()});return true;});return json({ok:true,alreadyRegistered:!created,message:created?"You're registered for this event.":"You're already registered."},created?201:200);}
if(!canManage(u))return json({error:"You do not have permission to create events."},403);const title=clean(b.title,100),description=clean(b.description,1800),category=clean(b.category,32),location=clean(b.location,140),startsAt=Number(b.startsAt),endsAt=Number(b.endsAt),capacity=Math.max(0,Math.min(500,Number(b.capacity)||0));if(!title||!description||!["tryout","tournament","community","training","other"].includes(category)||!validDate(startsAt)||!Number.isFinite(endsAt)||endsAt<=startsAt)return json({error:"Check the title, category, description and event dates."},400);const now=Date.now(),ref=await col.add({title,description,category,location,startsAt,endsAt,capacity,status:"published",registrationOpen:true,createdAt:now,updatedAt:now,createdBy:u.id});await store.collection("webAuditLogs").add({action:"event_created",eventId:ref.id,reviewerDiscordId:u.id,createdAt:now});return json({ok:true,id:ref.id},201);}
if(req.method==="PATCH"){if(!canManage(u))return json({error:"You do not have permission to manage events."},403);let b;try{b=await req.json();}catch{return json({error:"Invalid request."},400);}const id=clean(b.eventId,100),action=clean(b.action,30);if(!id)return json({error:"Event ID required."},400);const ref=col.doc(id),snap=await ref.get();if(!snap.exists)return json({error:"Event not found."},404);const now=Date.now();if(action==="status"){const status=clean(b.status,20);if(!["published","completed","cancelled"].includes(status))return json({error:"Invalid event status."},400);await ref.update({status,registrationOpen:status==="published",updatedAt:now});}
else if(action==="registration"){await ref.update({registrationOpen:!!b.open,updatedAt:now});}
else if(action==="attendance"){const discordId=clean(b.discordId,30),attendance=clean(b.attendance,20);if(!/^\d{17,20}$/.test(discordId)||!["attended","absent","registered"].includes(attendance))return json({error:"Invalid attendance update."},400);const rr=ref.collection("registrations").doc(discordId);const rs=await rr.get();if(!rs.exists)return json({error:"Registrant not found."},404);await rr.update({status:attendance,attendanceUpdatedAt:now,attendanceUpdatedBy:u.id});}
else return json({error:"Unknown event action."},400);await store.collection("webAuditLogs").add({action:"event_"+action,eventId:id,reviewerDiscordId:u.id,createdAt:now});return json({ok:true});}
if(req.method==="DELETE"){if(!canManage(u))return json({error:"You do not have permission."},403);return json({error:"Events are archived rather than deleted. Set their status to cancelled."},405);}
return json({error:"Method not allowed."},405);
}catch(e){console.error("Events endpoint failed:",e);return json({error:"Events are temporarily unavailable."},500);}};
