import { createHmac, timingSafeEqual, randomBytes } from "node:crypto";
import { initializeApp, getApps, cert } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";
let firestore;
function db(){if(firestore)return firestore;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("Firebase is not configured.");const credentials=JSON.parse(raw);if(credentials.private_key)credentials.private_key=credentials.private_key.replace(/\\n/g,"\n");if(!getApps().length)initializeApp({credential:cert(credentials)});firestore=getFirestore();return firestore;}
function session(req){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)return null;const raw=req.headers.get("cookie")||"";const part=raw.split(";").map(x=>x.trim()).find(x=>x.startsWith("bd_session="));if(!part)return null;const value=decodeURIComponent(part.slice(11));const dot=value.lastIndexOf(".");if(dot<1)return null;const payload=value.slice(0,dot),sig=value.slice(dot+1),expected=createHmac("sha256",secret).update(payload).digest("base64url");const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{const data=JSON.parse(Buffer.from(payload,"base64url").toString());return data.exp>Date.now()/1000?{id:String(data.id)}:null;}catch{return null;}}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
async function lookup(name){const r=await fetch("https://users.roblox.com/v1/usernames/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({usernames:[name],excludeBannedUsers:true})});if(!r.ok)throw new Error("Roblox lookup unavailable.");const found=(await r.json()).data?.[0];if(!found?.id)return null;const p=await fetch("https://users.roblox.com/v1/users/"+found.id);if(!p.ok)throw new Error("Roblox profile unavailable.");const profile=await p.json();return{id:String(found.id),name:String(found.name),displayName:String(found.displayName||found.name),description:String(profile.description||"")};}
export default async req=>{if(req.method!=="GET"&&req.method!=="POST")return json({error:"Method not allowed."},405);const user=session(req);if(!user)return json({error:"Sign in with Discord first."},401);try{const store=db(),ref=store.collection("webProfiles").doc(user.id);if(req.method==="GET"){const [p,player]=await Promise.all([ref.get(),store.collection("players").doc(user.id).get()]);const d=p.exists?p.data():{},v=player.exists?player.data():{};return json({linked:!!d.robloxUserId,roblox:d.robloxUserId?{id:String(d.robloxUserId),username:String(d.robloxUsername||"")}:null,pending:d.robloxChallengeExpiresAt>Date.now()?{id:String(d.pendingRobloxUserId||""),username:d.pendingRobloxUsername,code:d.robloxChallenge,expiresAt:d.robloxChallengeExpiresAt}:null,player:player.exists?{rank:String(v.rank||"E").toUpperCase(),kills:Math.max(0,Number(v.kills)||0)}:null});}
const body=await req.json().catch(()=>({}));if(body.action==="start"){const name=String(body.username||"").trim();if(!/^[A-Za-z0-9_]{3,20}$/.test(name))return json({error:"Enter a valid Roblox username."},400);const found=await lookup(name);if(!found)return json({error:"Roblox username not found."},404);const code="BD-"+randomBytes(4).toString("hex").toUpperCase(),expires=Date.now()+1800000;await ref.set({pendingRobloxUserId:found.id,pendingRobloxUsername:found.name,robloxChallenge:code,robloxChallengeExpiresAt:expires},{merge:true});return json({ok:true,username:found.name,code,expiresAt:expires});}
if(body.action==="verify"){const snap=await ref.get();if(!snap.exists)return json({error:"Start linking first."},400);const pending=snap.data();if(!pending.robloxChallenge||Number(pending.robloxChallengeExpiresAt)<=Date.now())return json({error:"Code expired. Generate another."},400);const found=await lookup(pending.pendingRobloxUsername);if(!found||found.id!==String(pending.pendingRobloxUserId)||!found.description.includes(pending.robloxChallenge))return json({error:"Code not found in the Roblox profile description. Save it and retry."},400);const lock=store.collection("robloxOwnership").doc(found.id);await store.runTransaction(async tx=>{const [owner,latest]=await Promise.all([tx.get(lock),tx.get(ref)]);if(owner.exists&&String(owner.data().discordId)!==user.id)throw new Error("This Roblox account is already linked to another Discord account.");if(!latest.exists||latest.data().robloxChallenge!==pending.robloxChallenge||Number(latest.data().robloxChallengeExpiresAt)<=Date.now())throw new Error("Verification expired. Start again.");tx.set(lock,{discordId:user.id,robloxUserId:found.id,robloxUsername:found.name,verifiedAt:Date.now()});tx.set(ref,{discordId:user.id,robloxUserId:found.id,robloxUsername:found.name,robloxDisplayName:found.displayName,robloxVerifiedAt:Date.now(),pendingRobloxUserId:FieldValue.delete(),pendingRobloxUsername:FieldValue.delete(),robloxChallenge:FieldValue.delete(),robloxChallengeExpiresAt:FieldValue.delete()},{merge:true});});return json({ok:true});}
if(body.action==="cancel"){await ref.set({pendingRobloxUserId:FieldValue.delete(),pendingRobloxUsername:FieldValue.delete(),robloxChallenge:FieldValue.delete(),robloxChallengeExpiresAt:FieldValue.delete()},{merge:true});return json({ok:true});}return json({error:"Unknown action."},400);
}catch(e){const message=String(e?.message||"");if(message.includes("already linked")||message.includes("expired"))return json({error:message},409);console.error("Roblox link error",e);return json({error:"Roblox linking is temporarily unavailable."},500);}};