import {createHmac,timingSafeEqual} from "node:crypto";
import {initializeApp,getApps,cert} from "firebase-admin/app";
import {getFirestore} from "firebase-admin/firestore";
let firestore;function db(){if(firestore)return firestore;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("Firebase is not configured.");const sa=JSON.parse(raw);if(sa.private_key)sa.private_key=sa.private_key.replace(/\\n/g,"\n");if(!getApps().length)initializeApp({credential:cert(sa)});firestore=getFirestore();return firestore;}
function user(req){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32)return null;const part=(req.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("bd_session="));if(!part)return null;let v;try{v=decodeURIComponent(part.slice(11));}catch{return null;}const i=v.lastIndexOf(".");if(i<1)return null;const p=v.slice(0,i),s=v.slice(i+1),e=createHmac("sha256",secret).update(p).digest("base64url"),a=Buffer.from(s),b=Buffer.from(e);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.exp>Date.now()/1000?{id:String(x.id)}:null;}catch{return null;}}
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
function publicTryout(t){if(!t)return null;return{id:String(t.id||""),status:String(t.status||"unknown"),createdAt:Number(t.createdAt)||0,endedAt:Number(t.endedAt)||0,serverLink:typeof t.serverLink==="string"&&t.serverLink.startsWith("https://")?t.serverLink:null,results:(Array.isArray(t.results)?t.results:[]).slice(-12).reverse().map((r,i)=>({match:Number(r.matchNumber)||i+1,winnerKills:Math.max(0,Number(r.winnerKills)||0),loserKills:Math.max(0,Number(r.loserKills)||0),timestamp:Number(r.timestamp)||0}))};}
export default async req=>{try{const store=db(),snap=await store.collection("tryouts").doc("server").get(),raw=snap.exists?snap.data():{},active=publicTryout(raw.active),history=(Array.isArray(raw.history)?raw.history:[]).map(publicTryout).filter(Boolean).sort((a,b)=>b.createdAt-a.createdAt).slice(0,12);if(req.method==="GET"){const u=user(req);let registration=null;if(u&&active){const r=await store.collection("webTryoutRegistrations").doc(active.id+"_"+u.id).get();if(r.exists){const x=r.data();registration={status:String(x.status||"registered"),registeredAt:Number(x.registeredAt)||0};}}return json({active,history,registration,signedIn:!!u});}
if(req.method!=="POST")return json({error:"Method not allowed."},405);const u=user(req);if(!u)return json({error:"Sign in with Discord to register."},401);if(!active||active.status!=="active")return json({error:"There is no active tryout accepting registrations."},409);const profile=await store.collection("webProfiles").doc(u.id).get(),p=profile.exists?profile.data():{};if(!p.robloxUserId||!p.robloxUsername)return json({error:"Link and verify your Roblox account before registering."},400);const ref=store.collection("webTryoutRegistrations").doc(active.id+"_"+u.id);const result=await store.runTransaction(async tx=>{const existing=await tx.get(ref);if(existing.exists)return false;tx.create(ref,{tryoutId:active.id,discordId:u.id,robloxUserId:String(p.robloxUserId),robloxUsername:String(p.robloxUsername).slice(0,32),status:"registered",registeredAt:Date.now()});return true;});return json({ok:true,alreadyRegistered:!result,message:result?"Your place has been registered.":"You're already registered for this tryout."},result?201:200);
}catch(e){console.error("Tryout portal failed:",e);return json({error:"Tryout information is temporarily unavailable."},500);}};
