import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {ArrowUpRight,Bell,BookOpen,CalendarDays,ClipboardList,ShieldCheck,Clock3,FileText,RefreshCw} from "lucide-react";
import {GlareHover} from "../components/GlareHover";
import {ScrollReveal} from "../components/ScrollReveal";
type Summary={pendingApplications:number;upcomingEvents:number;newsDrafts:number;announcementDrafts:number;recentActivity:{action:string;createdAt:number}[]};
const tools=[{to:"/admin/announcements",title:"ANNOUNCEMENT DESK",copy:"Publish official notices, save drafts and archive outdated updates.",icon:Bell},{to:"/admin/applications",title:"APPLICATION REVIEW",copy:"Review recruitment applications, request more information and record decisions.",icon:ClipboardList},{to:"/admin/events",title:"EVENT CONTROL",copy:"Create events, manage registration and record attendance.",icon:CalendarDays},{to:"/admin/content",title:"CONTENT DESK",copy:"Publish newsroom stories and induct verified members into the Hall of Fame.",icon:BookOpen}];
const metrics=[{key:"pendingApplications",label:"APPLICATIONS TO REVIEW",icon:ClipboardList},{key:"upcomingEvents",label:"UPCOMING EVENTS",icon:CalendarDays},{key:"newsDrafts",label:"NEWS DRAFTS",icon:FileText},{key:"announcementDrafts",label:"NOTICE DRAFTS",icon:Bell}] as const;
export function AdminDashboardPage(){const [summary,setSummary]=useState<Summary|null>(null),[state,setState]=useState<"loading"|"ready"|"denied"|"error">("loading"),[refreshing,setRefreshing]=useState(false);
async function load(){setRefreshing(true);try{const r=await fetch("/.netlify/functions/admin-overview",{credentials:"same-origin",cache:"no-store"});if(r.status===401||r.status===403){setState("denied");setSummary(null);return;}if(!r.ok)throw Error();setSummary(await r.json());setState("ready");}catch{setState("error");}finally{setRefreshing(false);}}
useEffect(()=>{load();},[]);
return <main className="inner-page"><section className="page-hero public-page-hero"><div className="section-kicker">STAFF ONLY / OPERATIONS</div><h1>THE BD<br/><em>COMMAND.</em></h1><p>One headquarters for the staff tools that keep BLACK DRAGONS organised.</p></section><section className="section-pad admin-dashboard"><div className="admin-dashboard-heading"><div><div className="section-kicker">STAFF CONTROL CENTRE</div><h2>THE LIVE<br/><em>OVERVIEW.</em></h2></div><button className="button button-quiet admin-refresh" onClick={load} disabled={refreshing}><RefreshCw size={14}/>{refreshing?"UPDATING…":"REFRESH"}</button></div>
{state==="loading"?<div className="leader-empty large-empty">Verifying your staff access and loading operations…</div>:state==="denied"?<div className="admin-access-state"><ShieldCheck size={27}/><h3>STAFF ACCESS REQUIRED.</h3><p>This control centre is restricted to current Discord staff with a configured dashboard role. Signing in alone does not grant access.</p></div>:state==="error"?<div className="admin-access-state"><ShieldCheck size={27}/><h3>OVERVIEW UNAVAILABLE.</h3><p>The staff summary could not be loaded. Check the Netlify configuration and try again.</p><button className="button button-quiet" onClick={load}>TRY AGAIN</button></div>:summary&&<><div className="admin-live-status"><span/> LIVE STAFF DATA · UPDATED {new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</div><div className="admin-metrics-grid">{metrics.map((metric,i)=>{const Icon=metric.icon;return <ScrollReveal key={metric.key}><article className="admin-metric-card"><div><Icon size={19}/><span>0{i+1} / OPERATIONS</span></div><strong>{Number(summary[metric.key]||0).toLocaleString("en-US")}</strong><small>{metric.label}</small></article></ScrollReveal>;})}</div><div className="admin-activity"><div className="section-kicker">RECENT AUDIT TRAIL</div><h3>THE LAST<br/><em>DECISIONS.</em></h3>{summary.recentActivity.length?summary.recentActivity.map((item,i)=><article key={i}><Clock3 size={15}/><span>{item.action.replace(/_/g," ").toUpperCase()}</span><time>{new Date(item.createdAt).toLocaleString()}</time></article>):<p>No recent staff actions have been recorded.</p>}</div></>}
<div className="admin-tools-heading"><div className="section-kicker">STAFF WORKSPACES</div><h2>CHOOSE YOUR<br/><em>OPERATION.</em></h2></div><div className="admin-tool-grid">{tools.map((tool,i)=>{const Icon=tool.icon;return <ScrollReveal key={tool.to}><Link to={tool.to} className="admin-tool-link"><GlareHover width="100%" height="100%" background="#111115" borderRadius="4px" borderColor="#765a3d" glareColor="#d7a65d" glareOpacity={.14} glareSize={150}><article className="admin-tool-card"><span className="section-kicker">CONTROL / 0{i+1}</span><Icon size={27}/><h3>{tool.title}</h3><p>{tool.copy}</p><span>OPEN CONTROL <ArrowUpRight size={14}/></span></article></GlareHover></Link></ScrollReveal>;})}</div><p className="admin-dashboard-note"><ShieldCheck size={15}/> Dashboard data and staff permissions are checked by the server. Only authorised Discord roles can access the live overview.</p></section></main>;}