import { useEffect, useState } from "react";
import { ArrowRight, Crown, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import { ParticleField } from "../components/ParticleField";
import { SpotlightCard } from "../components/SpotlightCard";
import { TiltedCard } from "../components/TiltedCard";
import "./LeaderboardPage.css";
type Player={discordId:string;displayName:string;discordUsername:string|null;avatar:string|null;profileLinked:boolean;robloxUsername:string|null;kills:number;rank:string};
type TitleHolder={discordId:string;displayName:string;discordUsername:string;avatar:string|null;profileLinked:boolean;robloxUsername:string|null};
type TitleSlot={key:string;order:number;title:string;holders:TitleHolder[]};
type State="loading"|"ready"|"setup"|"error";
const discordProfile=(id:string)=>window.open("https://discord.com/users/"+encodeURIComponent(id),"_blank","noopener,noreferrer");
export function LeaderboardPage(){
 const [players,setPlayers]=useState<Player[]>([]),[titleSlots,setTitleSlots]=useState<TitleSlot[]>([]);
 const [state,setState]=useState<State>("loading"),[titleState,setTitleState]=useState<"ready"|"empty"|"unavailable">("unavailable"),[holderLookupStatus,setHolderLookupStatus]=useState<"ready"|"unavailable">("ready"),[updatedAt,setUpdatedAt]=useState("");
 useEffect(()=>{let active=true;fetch("/.netlify/functions/leaderboard").then(async r=>{if(r.status===503)throw new Error("setup");if(!r.ok)throw new Error("request");return r.json();}).then((d:{players?:Player[];titleSlots?:TitleSlot[];titleStatus?:"ready"|"empty"|"unavailable";holderLookupStatus?:"ready"|"unavailable";updatedAt?:string})=>{if(!active)return;setPlayers(d.players||[]);setTitleSlots(d.titleSlots||[]);setTitleState(d.titleStatus||"unavailable");setHolderLookupStatus(d.holderLookupStatus||"ready");setUpdatedAt(d.updatedAt||"");setState("ready");}).catch((e:Error)=>{if(active)setState(e.message==="setup"?"setup":"error");});return()=>{active=false;};},[]);
 const featured=players[0],roster=players.slice(1);
 return <main className="inner-page">
  <section className="page-hero leaderboard-hero"><ParticleField/><div className="section-kicker">THE BLACK DRAGONS RECORD</div><h1>LEGENDS ARE<br/><em>NOT GIVEN.</em></h1><p>Titles are claimed through recognition. Kills are recorded through battle. Two boards. Two different legacies.</p><div className="page-hero-mark"><Trophy size={55}/><span>THE ORDER • THE KILLBOARD</span></div></section>
  <section className="section-pad monarch-section"><div className="leaderboard-heading"><div><div className="section-kicker">01 / THE TITLE HOLDERS</div><h2>THE<br/><em>MONARCHS.</em></h2></div><div className="leader-live"><Crown size={15}/> TITLE ARCHIVE</div></div><p className="monarch-intro">Every configured Monarch title has its own place in the order. Holders are shown from Discord; vacant titles remain open for the next name to claim.</p>
   {state==="loading"?<div className="leader-empty large-empty">Loading the Monarch order…</div>:titleState==="unavailable"?<div className="leader-empty large-empty">Title configuration is temporarily unavailable.</div>:titleSlots.length===0?<div className="leader-empty large-empty">The Monarch title list could not be loaded.</div>:<>{holderLookupStatus==="unavailable"&&<div className="leader-empty monarch-lookup-warning">Discord could not verify current title holders. Vacant titles are shown as placeholders until member lookup is available.</div>}<div className="monarch-grid">{titleSlots.map((slot,index)=>{const holder=slot.holders[0];return <TiltedCard key={slot.key} className={index===0?"monarch-tilt monarch-tilt-first":"monarch-tilt"}><SpotlightCard className={index===0?"monarch-card monarch-card-first":"monarch-card"}><span className="monarch-index">{String(index+1).padStart(2,"0")} / TITLE</span><div className="monarch-card-title">{slot.title}</div>{holder?<><div className="monarch-card-avatar">{holder.avatar?<img src={holder.avatar} alt="" loading="lazy"/>:<Crown size={28}/>}</div><div className="monarch-card-name">{holder.displayName}</div><div className="monarch-card-handle">@{holder.discordUsername}</div><button type="button" className="monarch-card-profile" onClick={()=>discordProfile(holder.discordId)}>VIEW PROFILE <ArrowRight size={13}/></button></>:<div className="monarch-vacant"><div className="monarch-vacant-sigil"><Crown size={25}/></div><strong>NO CURRENT HOLDER</strong><span>COULD BE YOU</span></div>}</SpotlightCard></TiltedCard>})}</div></>}
  </section>
  <section className="section-pad leaderboard-page killboard-section"><div className="leaderboard-heading"><div><div className="section-kicker">02 / VERIFIED COMBAT RECORDS</div><h2>THE<br/><em>KILLBOARD.</em></h2></div><div className="leader-live"><span className={state==="ready"?"status-dot":"status-dot status-wait"}/>{state==="ready"?"LIVE DATA":"DATA STATUS: "+state.toUpperCase()}</div></div>
   {state==="loading"?<div className="leader-empty large-empty">Fetching verified player records…</div>:state==="setup"?<div className="leader-empty large-empty">The secure Firebase connection needs its Netlify service-account setting before player records can appear.</div>:state==="error"?<div className="leader-empty large-empty">Player rankings could not be loaded. Please check back shortly.</div>:players.length===0?<div className="leader-empty large-empty">No verified player records are available yet. The board will appear here when records are published.</div>:<div className="kill-roster">
    {featured&&<div className="kill-feature-tilt"><SpotlightCard className="kill-featured"><span className="kill-featured-kicker"><Crown size={13}/> CURRENT LEADER</span><div className="kill-featured-avatar">{featured.avatar?<img src={featured.avatar} alt="" loading="lazy"/>:<span>BD</span>}</div><h3>{featured.profileLinked?<Link to={"/members/"+featured.discordId}>{featured.displayName}</Link>:featured.displayName}</h3><small className="kill-featured-rank">{featured.rank} • RANK</small><strong className="kill-featured-kills">{Number(featured.kills||0).toLocaleString("en-US")}</strong><small className="kill-roster-label">VERIFIED KILLS</small><button type="button" className="monarch-card-profile" onClick={()=>discordProfile(featured.discordId)}>VIEW PROFILE <ArrowRight size={13}/></button></SpotlightCard></div>}
    {roster.length>0&&<div className="kill-roster-grid">{roster.map((p,i)=><TiltedCard key={p.discordId} className="kill-card-tilt"><SpotlightCard className="kill-roster-card kill-roster-reactbits"><span className="kill-roster-index">{String(i+2).padStart(2,"0")}</span><div className="kill-roster-avatar">{p.avatar?<img src={p.avatar} alt="" loading="lazy"/>:<span>BD</span>}</div><div className="kill-roster-name">{p.profileLinked?<Link to={"/members/"+p.discordId}>{p.displayName}</Link>:<strong>{p.displayName}</strong>}</div><small className="kill-roster-rank">{p.rank} • RANK</small><strong className="kill-roster-kills">{Number(p.kills||0).toLocaleString("en-US")}</strong><small className="kill-roster-label">VERIFIED KILLS</small></SpotlightCard></TiltedCard>)}</div>}
   </div>}
   {updatedAt&&<p className="data-updated">LAST UPDATED · {new Date(updatedAt).toLocaleString()}</p>}
  </section>
  <section className="clan-bottom section-pad"><div className="section-kicker">YOUR NAME COULD BE NEXT</div><h2>MAKE YOUR<br/><em>MARK.</em></h2><p>Build your record and earn your place among the dragons.</p><Link to="/ranks" className="button button-primary">EXPLORE THE RANKS <ArrowRight size={16}/></Link></section>
 </main>;
}
