import { useEffect,useState } from "react";
import { Award,Clock3,Flame,LockKeyhole,ShieldCheck,TrendingUp } from "lucide-react";
import { GlareHover } from "../components/GlareHover";
import { ScrollReveal } from "../components/ScrollReveal";
type Entry={action:string;rank:string;previousRank:string|null;kills:number;timestamp:number;reason:string|null};
type Data={player:{rank:string;kills:number}|null;nextRank:{rank:string;threshold:number}|null;progress:number;remaining:number;achievements:{id:string;title:string;description:string;threshold:number;earned:boolean}[];history:Entry[]};
const fmt=(n:number)=>Number(n||0).toLocaleString("en-US");
const when=(n:number)=>n?new Date(n).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"}):"Date unavailable";
export function MemberProgressionPanel(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;fetch("/.netlify/functions/member-progression",{credentials:"same-origin",cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Progression unavailable.");return b as Data;}).then(b=>{if(live)setData(b);}).catch(e=>{if(live)setError(e instanceof Error?e.message:"Could not load progression.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 return <ScrollReveal><section className="member-progression"><div className="member-progression-heading"><div><span className="section-kicker">04 / YOUR LEGACY</span><h2>THE ROAD TO <em>THE TOP.</em></h2></div><span className="account-secure"><TrendingUp size={14}/> LIVE PLAYER DATA</span></div>
 {loading?<div className="progression-empty">SYNCING YOUR VERIFIED RECORD…</div>:error?<div className="progression-empty progression-error">{error}</div>:!data?.player?<div className="progression-empty">No official player record is linked to this Discord account yet. Once the bot registers your rank, your progression will appear here.</div>:<>
 <GlareHover width="100%" height="100%" background="#101115" borderRadius="4px" borderColor="#765a3d" glareColor="#d7a65d" glareOpacity={0.1} glareSize={150} className="progression-rank-card"><div className="progression-card-inner"><div className="progression-rank-top"><span className="section-kicker">CURRENT RANK</span><span className="progression-live"><i/> VERIFIED</span></div><div className="progression-rank-main"><div><small>BLACK DRAGONS</small><strong>{data.player.rank}</strong></div><div className="progression-kills"><small>TOTAL VERIFIED KILLS</small><strong>{fmt(data.player.kills)}</strong></div></div>
 {data.nextRank?<><div className="progression-bar-label"><span>NEXT RANK · {data.nextRank.rank}</span><span>{Math.round(data.progress)}%</span></div><div className="progression-track"><span style={{width:data.progress+"%"}}/></div><div className="progression-foot"><span>{fmt(data.remaining)} kills to go</span><span>{fmt(data.nextRank.threshold)} required</span></div></>:<div className="progression-max"><ShieldCheck size={15}/> TOP RANK ACHIEVED · Z</div>}</div></GlareHover>
 <div className="progression-section-title"><span><Award size={15}/> KILL MILESTONES</span><small>{data.achievements.filter(a=>a.earned).length} / {data.achievements.length} UNLOCKED</small></div><div className="progression-achievements">{data.achievements.map(a=><div className={`progression-achievement ${a.earned?"is-earned":"is-locked"}`} key={a.id}><span className="progression-achievement-icon">{a.earned?<Flame size={17}/>:<LockKeyhole size={15}/>}</span><span><strong>{a.title}</strong><small>{a.description}</small></span><b>{a.earned?"UNLOCKED":fmt(a.threshold)}</b></div>)}</div>
 <div className="progression-section-title progression-history-title"><span><Clock3 size={15}/> RANK HISTORY</span><small>OFFICIAL BOT RECORD</small></div>{data.history.length?<div className="progression-history">{data.history.map((e,i)=><article className="progression-history-item" key={e.timestamp+"-"+i}><i className="progression-history-dot"/><div className="progression-history-content"><div><strong>{e.action.replace(/_/g," ").toUpperCase()}</strong><time>{when(e.timestamp)}</time></div><p>{e.previousRank?e.previousRank+" → ":""}{e.rank} <span>·</span> {fmt(e.kills)} kills</p>{e.reason&&<small>{e.reason}</small>}</div></article>)}</div>:<div className="progression-empty">No rank changes have been recorded yet. New official changes will appear here automatically.</div>}
 </>}</section></ScrollReveal>;
}